config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get "auth/:provider/callback", to: "google_oauth#update"
  get "auth/failure", to: redirect("/")

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/register', to: "users#new"
  post '/register', to: "users#create"

  get '/dashboard', to: "users#show", as: "dashboard"

  resources :users, only: [:create]

  namespace :user do
    resources :topics,  only: [:new, :create, :show, :update] do

      resources :questions, only: [:new, :create, :show, :update] do
        resources :links, only: [:new, :create, :update]
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bing_link.rb
class BingLink < SimpleDelegator
  attr_reader  :title,
               :bing_site_link_text,
               :question,
               :bing_display_text

  def initialize(link_data, question)
    @title = link_data[:name]
    @bing_site_link_text = link_data[:url]
    @bing_display_text = link_data[:displayUrl]
    @question = question
  end

end

app/models/google_oauth_token.rb
class GoogleOauthToken < ApplicationRecord
  belongs_to :user, dependent: :destroy

  validates_presence_of :token
                        :refresh_token

  validates :user_id, uniqueness: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :question, dependent: :destroy

  validates_presence_of :name, :website_link_text

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :topic, dependent: :destroy
  has_many :links

  validates_presence_of :title
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :questions

  validates_presence_of :title

  enum status: [:disable, :enable]

  def last_created_question
    questions.order(:created_at).last
  end

  def has_questions
    true if questions.length > 0
  end

  def created_at_format
    self.created_at.strftime("%a, %d %B of %Y")
  end

  def updated_at_format
    self.updated_at.strftime("%a, %d %B of %Y")
  end

  def in_progress
    true if self.complete == false
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :topics
  has_many :questions, through: :topics
  has_one :google_oauth_token

  validates_presence_of :first_name,
                        :last_name,
                        :email

  validates :email, uniqueness: true

  has_secure_password validations: false

  def self.from_omniauth(data)
    where(email: data["info"]["email"]).first_or_initialize do |user|
      user.first_name = data["info"]["first_name"]
      user.last_name = data["info"]["last_name"]
      user.email = data["info"]["email"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/google_oauth_controller.rb
class GoogleOauthController < ApplicationController

  def update
    data = request.env["omniauth.auth"]
    if data["credentials"] == nil
      flash[:notice] = "Google Authorization was unable to be completed."
      redirect_to root_path
    else
      user = User.from_omniauth(data)
      refresh_token = data.credentials.refresh_token
      if user.id != nil
        session[:user_id] = user.id
        user.google_oauth_token.update(refresh_token: refresh_token) if refresh_token.present?
        flash[:notice] = "You have successfully logged in!"
        redirect_to dashboard_path
      elsif user.save
        GoogleOauthToken.create(token: data.credentials.token, user: user, refresh_token: refresh_token)
        session[:user_id] = user.id
        flash[:notice] = "Account Created!"
        redirect_to dashboard_path
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash[:error] = "Looks like your email or password is invalid"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/topic/questions_controller.rb
class Topic::QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    topic = Topic.find(params[:id])
    @question = topic.questions.create(question_params)

    redirect_to user_topic_path(topic)
  end

  private

  def question_params
    params.require(:topic).permit(:title)
  end

end

app/controllers/user/links_controller.rb
class User::LinksController < ApplicationController
protect_from_forgery except: :new
  def new
    if params["bing_website_text"] != nil
      @link = Link.new(website_link_text: params[:bing_website_text])
    else
      @link = Link.new
    end
      @question = Question.find(params[:question_id])
      @topic = Topic.find(params[:topic_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    question = Question.find(params[:question_id])
    topic = Topic.find(params[:topic_id])
    link = question.links.create(link_params)

    redirect_to user_topic_path(topic, q_id: params[:question_id])
  end

  def update

  end

  private

  def link_params
    params.require(:link).permit(:link, :name, :website_link_text)
  end

end

app/controllers/user/questions_controller.rb
class User::QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    topic = Topic.find(params[:topic_id])
    question = topic.questions.create(question_params)
    redirect_to user_topic_path(topic, q_id: params[:question_id])
  end

  def show
    topic = Topic.find(params[:topic_id])
    redirect_to user_topic_path(topic, q_id: params[:question_id])
  end

  def update
    question = Question.find(params[:id])
    question.update(notes_text: params[:notes_text])

    @topic = Topic.find(params[:topic_id])
    redirect_to user_topic_path(@topic, q_id: params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end
end

app/controllers/user/topics_controller.rb
class User::TopicsController < ApplicationController
  def new
    @topic = Topic.new
    @user = current_user
  end

  def index
  end

  def show
    if params[:q_id]
      topic = Topic.find(params[:id])
      question = Question.find(params[:q_id])
      @facade = TopicFacade.new(topic, question, user)
    else
      topic = Topic.find(params[:id])
      @facade = TopicFacade.new(topic, user)
    end
  end

  def update
    topic = Topic.find(params[:id])
    if params[:topic_notes] != nil
      topic.update(topic_notes: params[:topic_notes])
      redirect_to user_topic_path(topic)
    else
    topic.update(update_params)
    redirect_to dashboard_path
    end
  end

  def create
    topic = current_user.topics.create(topic_params)
    if topic.save
      flash[:notice] = "Topic created"
      redirect_to user_topic_path(topic)
    else
      redirect_to new_user_topic_path
      flash[:error] = "Topic couldn't be saved, fill all the forms"
    end
  end

  private

  attr_reader :user

  def topic_params
    params.require(:topic).permit(:title, :goal)
  end

  def update_params
    params.fetch(:topic, {}).permit(:status, :complete, :topic_notes)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Registered as #{user.first_name} #{user.last_name}"
      redirect_to dashboard_path
    else
      flash[:error] = "Please check your email and password information"
      redirect_to register_path
    end
  end

  def show
    @facade = UserDashboardFacade.new(current_user)
  end

private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
  <head>
    <title>RabbitHole</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag "application" %>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>

    <header>
      <%= render 'partials/nav' %>
    </header>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <div class="content">
        <%= yield %>
    </div>
  </div>

  </body>

</html>

app/views/partials/_nav.html.erb
<nav class="navbar-default">
  <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Down the Rabbit Hole</a>
      </div>
    <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
      <li><%=link_to "My Dashboard", dashboard_path, class: 'btn btn-primary'%></li>
      <li><%=link_to "Logout", logout_path, method: :delete, class: 'btn btn-primary' %></li>
      </ul>
    <%else%>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/register" class: 'btn btn-primary'><span class="glyphicon glyphicon-user"></span> Register</a></li>
        <li><a href="/login" class: 'btn btn-primary'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    <%end%>
  </div>
</nav>

app/views/partials/_question_ask_bar.html.erb
<% if @facade.topic_question_count == 0 %>
  <h3> Now ask a question that you have to get started with your research! </h3>
  <div align="right">
  <h1> ↓↓↓ </h1>
  </div>
<% end %>
<%= form_for @facade.new_question, url: user_topic_questions_path(@facade.topic) do |f| %>
  <%= f.text_field :title, size: 100 %>
  <%= f.submit "Ask New Question", class: 'btn btn-primary' %>
<% end %>

app/views/partials/_question_notes.html.erb
<div class="container-fluid">
<h3>Notes</h3>
<%= simple_form_for @facade.current_question, url: user_topic_question_path(@facade.topic, @facade.current_question) do |f| %>
  <div class="question_note_area">
    <% if !@facade.current_question.notes_text %>
      <%= text_area_tag(:notes_text, "Write notes here!", size: "120x6") %>
    <% else %>
      <%= text_area_tag(:notes_text, "#{@facade.current_question.notes_text}", size: "120x6") %>
    <% end %>
  </div>
  <div class="question_note_save">
    <%= f.submit "Save Note", class: 'btn btn-secondary' %>
  </div>
<% end %>
</div>

app/views/partials/_question_show.html.erb
<div class="container_fluid">
<div class="question_title">
<h2><%= @facade.current_question.title %></h2>
</div>


    <%= render 'partials/question_notes' %>


<div class="card">
  <div class="bing_results">
    <h3>Bing results</h3>
      <% @facade.bing_search(@facade.current_question).each do |link| %>
        <div class="search_results">
          <%= link_to "#{link.title}", link.bing_site_link_text, target: "_blank" %> <%= link_to 'Save Link', "#{new_user_topic_question_link_url(@facade.topic, @facade.current_question)}.js?bing_website_text=#{link.bing_site_link_text}", remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary'%><br>
          <%=link.bing_display_text%>
        </div>
      <%end%>
  </div>
</div>

<div class="card">
  <div class="all_saved_links">
    <h3>Saved Links</h3>

    <%= link_to 'Add New Link', "/user/topics/#{@facade.topic.id}/questions/#{@facade.current_question.id}/links/new.js", remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary' %>

    <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
      </div>
    </div>

    <% @facade.current_question_links.each do |link| %>
      <div class="saved_link">
        <%= link_to "#{link.name}", "http://#{link.website_link_text}", target: "_blank" %> <br>
        <%= link.website_link_text.truncate(65) %>
      </div>
    <%end%>
  </div>
</div>
</div>

app/views/partials/_topic_notes.html.erb
<%= form_for [@facade.user, @facade.topic], url: user_topic_path(@facade.topic), method: :patch do |f|  %>
  <div class="topic_note_area">
    <% if !@facade.topic.topic_notes %>
      <%= text_area_tag(:topic_notes, "Write topic notes here!", size: "120x6") %>
    <% else %>
      <%= text_area_tag(:topic_notes, "#{@facade.topic.topic_notes}", size: "120x6") %>
    <% end %>
  </div>
  <div class="topic_note_save">
    <%= f.submit "Save Note", class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/user/links/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Add a link to the current question</h4>
</div>
<div class="modal-body">
  <div id="new_link_form">
    <% if @link.website_link_text != nil %>

      <%= simple_form_for @link, url: user_topic_question_links_path(@topic, @question) do |f| %>
      <%=f.input :name, label: 'Include a brief description', input_html: { maxlength: 75, :size => 40 } %>
      <%=f.input :website_link_text, label: 'Add the full website URL', placeholder: "#{@link.website_link_text}", input_html: { maxlength: 255, :size => 40 } %>
      <%= f.button :button, "Create Link", class: 'btn btn-primary'%>
      <%end%>

    <%else%>
      <%= simple_form_for @link, url: user_topic_question_links_path(@topic, @question) do |f| %>
      <%=f.input :name, label: 'Include a brief description', placeholder: 'Ex: ABA recent graduate data', input_html: { maxlength: 75, :size => 40 } %>
      <%=f.input :website_link_text, label: 'Add the full website URL', placeholder: 'Ex: www.americanbar.org/groups/legal_education/resources/statistics/', input_html: { maxlength: 255, :size => 40 } %>
      <%= f.button :button, "Create Link", class: 'btn btn-primary'%>
      <% end %>

    <%end%>
  </div>
</div>

app/views/user/links/new.js.erb
$("#modal-window").find(".modal-content").html("<%= escape_javascript render(:partial => 'new') %>");
$("#modal-window").modal();

app/views/user/topics/new.html.erb
<div class="card">
<div class="new_topic_form">
  <%= form_for [@user, @topic], url: user_topics_path do |f|  %>

    <p class="form_text">What do you want to learn about? What do you want to learn to do? Type your response below to create a new topic.</p>
    <%= f.text_field :title, size: 100 %>

    <p class="form_text">We support your journey to learn something new. What do you want to do, make, or create once the hard work pays off?</p>
    <%= f.text_field :goal, size: 100 %>

    <br><%= f.submit "Create New Topic", class: 'btn btn-primary' %>

  <% end %>
</div>
</div>

app/views/user/topics/show.html.erb
<nav class="sidebar-nav navbar-fixed">
  <div class="container-fluid">
      <h2>Questions Asked:</h2>
      <ul>
      <% @facade.topic_questions.each do |question|%>
      <li><%= link_to "#{question.title}", user_topic_question_path(@facade.topic.id, question_id: question.id) %></li><br>
      <% end %>
      </ul>
  </div>
</nav>


<div class="container">

<div class="topic">

<div class="topic_body">
  <div class="topic_header">
    <div class="learning_about">
      <p class="headline">Learning about</p>
      <h1><%=@facade.topic.title%></h1>
    </div>
    <div class="goal">
      <p class="headline">Goal</p>
      <h1><%=@facade.topic.goal%></h1>
    </div>
  </div>

  <div class="ask_bar">
    <%= render 'partials/question_ask_bar' %>
  </div>

  <div class="topic_show_notes">
    <%= render 'partials/topic_notes' %>
  </div>

    <div class="question_show_topic_page">
      <% if @facade.topic_has_questions %>
      <%= render 'partials/question_show' %>
      <%else%>
      <h3>Ask a question and begin exploring!</h3>
      <%end%>
    </div>

  <div class="topic_complete_button">
  <% if @facade.topic_in_progress %>
    <%= button_to "Research Complete", user_topic_path(@facade.topic), :params => {:topic => { complete: true }}, method: :put, class: 'btn btn-secondary' %>
  <% else %>
    <%= button_to "Reopen Research", user_topic_path(@facade.topic), :params => {:topic => { complete: false }}, method: :put, class: 'btn btn-secondary' %>
  <%end %>
  </div>
</div>
</div>
</div>

app/views/users/new.html.erb
  <div class="card">
    <div class="form-login">
      <h2 class="form-login-heading">register now</h2>
      <div class="login-wrap">
      <%= form_for @user do |form| %>
          <div class="login_form_field">
            <%= form.label :email %>
            <%= form.email_field :email %>
          </div>
          <br>
          <div class="login_form_field">
            <%= form.label :first_name %>
            <%= form.text_field :first_name %>
          </div>
          <br>
          <div class="login_form_field">
            <%= form.label :last_name %>
            <%= form.text_field :last_name %>
          </div>
          <br>
          <div class="login_form_field">
            <%= form.label :password %>
            <%= form.password_field :password %>
          </div>
          <br>
          <div class="login_form_field">
            <%= form.label :Confirm_password %>
            <%= form.password_field :password_confirmation %>
          </div>
          <br>
          <div class="login_submit">
            <%= form.submit 'Register', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </end>
        <hr>
        <div class="login-social-link centered">
          <p>Register using your Google account</p>
            <%= link_to "Register with Google", "/auth/google_oauth2", class: 'btn btn-primary' %>
        </div>
      </div>
    </form>
  </div>

app/views/users/show.html.erb
<h1> <%= @facade.full_name%>'s Topic Dashboard</h1>
<% if @facade.user_topics_count == 0 %>
  <h3> Start your journey by creating a topic about whatever you want to research! The sky's the limit! </h3>
  <h1> ↓ </h1>
<% end %>

<div class="New_topic">
  <%= link_to "Create New Topic", new_user_topic_path, class: 'btn btn-primary' %>
</div>

<div class="content">
  <div class="container-fluid">
    <div class="row">
        <div class="card">
          <div class="card-header card-header-primary">
            <h2 class="card-title ">Research In Progress</h2>
          </div>
          <div class="card-body in_progress_topics">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                </thead>
                <tbody>
                  <%@facade.in_progress_topics.each do |topic| %>
                  <tr class="topic_link">
                  <td>
                    <%= link_to topic.title,user_topic_path(topic) %>
                  </td>
                  <td>
                    Research began on <%=topic.created_at_format %>
                  </td>
                  <td>
                    <%= button_to "Research Complete", user_topic_path(topic), :params => {:topic => { complete: true }}, method: :put, class: 'btn btn-secondary' %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="content">
  <div class="container-fluid">
    <div class="row">
        <div class="card">
          <div class="card-header card-header-primary">
            <h2 class="card-title ">Completed Research</h2>
          </div>
          <div class="card-body complete_topics">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                </thead>
                <tbody>
                  <%@facade.complete_topics.each do |topic| %>
                  <tr class="topic_link">
                  <td class="complete_research">
                    <%= link_to topic.title,user_topic_path(topic) %>
                  </td>
                  <td>
                    Research updated on <%=topic.updated_at_format %>
                  </td>
                  <td>
                    <%= button_to "Reopen Research", user_topic_path(topic), :params => {:topic => { complete: false }}, method: :put, class: 'btn btn-secondary' %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section class="welcome-text">
<h1> Welcome Down the Rabbit Hole</h1>
<h3>"...where you never know less than you do right now."</h3>
<p> Inspired by Sandi Metz </p>
<% if current_user == nil %>
<br />
<br />
<br />
<h4>This application is a tool to help you organize your research. Start by making a account, or logging in if you've registered before!<br /></h4>
<% end %>
</section>